# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: db62e82cb2f7bad0fde662d05e41f1686dc17bad1ec5d4c122f156b511494bcee17088f325dafda404a58f67d7e3e0c4c60e2289f76c37c14311cc0aae35fc53

test:
  secret_key_base: f3af42a6be767d4c9eb07b1289ab6b6e1634ff256558edd6bc132c30aeaddecc81e1a6546f865faf04087648d59c5175eefec8aff1878d7367c255422626b31b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
